generatorName: scala-http4s
outputDir: samples/server/petstore/scala/http4s
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/scala-http4s
additionalProperties:
  hideGenerationTimestamp: "true"
